# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gerard Nijssen
email: info@gerardnijssen.nl
description: "Gerard Nijssen started in 1989, after studying History, as a freelance image researcher. He has been working for national and international award-winning productions in film and television for 25 years. Nijssen has also worked for a variety of museums and exhibitions." #max 272 tekens
baseurl: http://gerardnijssen.nl  # the subpath of your site, e.g. /blog
url: http://gerardnijssen.nl # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
facebook_username:
copyright: Amsterdam, Netherlands
imdb_url: http://www.imdb.com/name/nm3063512/
telephone_number: +31612345678
homepage_image: /img/gn_placeholder.png
favicon_image: /img/gn_empty.png
year: 2017
paginate: 1

collections:
  work:
    title: Work
    output: true
    permalink: "/:title/"

defaults:
  scope:
    path: ''
    type: work
  values:
    author: Gerard Nijssen
    layout: work
    title:
    image:
    image_description:
    vimeo:
    copyright_country_year: Gerard Nijssen, Netherlands, 2017
    work_url: http://

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
